# Generated by Django 5.1.5 on 2025-01-21 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_type', models.CharField(choices=[('BR', 'Bronze'), ('SI', 'Silver'), ('GO', 'Gold')], max_length=2, unique=True)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_cycle', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LotteryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.PositiveIntegerField()),
                ('amount_won', models.DecimalField(decimal_places=2, max_digits=10)),
                ('win_date', models.DateField(auto_now_add=True)),
                ('cash_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.cashbox')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.familymember')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.PositiveIntegerField()),
                ('is_winner', models.BooleanField(default=False)),
                ('cash_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.cashbox')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.familymember')),
            ],
            options={
                'unique_together': {('member', 'cash_box', 'cycle')},
            },
        ),
    ]
